### PR TITLE
Refactoring of coverage parsing mechanism

### PR DESCRIPTION
**Pull request by sergio1990**
## Overall information

This PR provides the following changes:

- refactor of the part which is responsible for reading and parsing simplecovrcov reports
- some of the MetricFu rules are marked as BUG
- a fix (a little bit dirty) of the translations issue, when use this plugin with SonarQube 6.2

We had a conversation in a Gmail, and I've written that I have a very poor Java skills, so, please, if something is not so acceptable in the Java community just say me 😄 

Right now I want to expand each item with a bit of additional information.

### Refactoring of parsing SimpleCovRcov reports

I've extracted some data classes and rewritten the whole parsing process due to make it more clear and easier for understanding.

Also, as a part of this refactoring I've made a possibility to read either RSpec results or Minitest results.

All data models has been covered by unit tests.

### Some of the MetricFu rules are marked as BUG

By default all rules were considered as _CODE SMELLS_. But this is a bit wrong, because some of the rules are really _BUG_. Also this small improvement gave a food for SonarQube to measure _Reliability_ level of a project.

### A fix of the translations issue, when use this plugin with SonarQube 6.2

This is a one in which I'm not confident. The fix is very dirty and do not like such approaches, but haven't enough knowledge to make it more beautiful.

Basically the problem is the following: when I've used this plugin with SonarQube 5.5 all is fine. And it's logically, cause this plugin is written for that SQ version. But when I've used with SQ 6.2, mostly it was working well, but I've noticed a problems with translations. For example, in a header we have `Projects` link, but instead I saw `projects.page` string, which is translation key. Based on the small story above a have several questions:

- How it's possible to use plugins, which has been written for one version of SQ with another one? Maybe each plugin has inside (as dependency) all needed libraries to be called in a some context. It's just a suggestion.
- For example, my suggestion is true (or partially true): why plugin affects on the whole site?

I'm looking forward for a response!

### CODE REVIEW

**Comment by sergio1990** [comment]
[There](https://github.com/SonarSource/sonarqube/blob/6.2/server/sonar-web/core.properties), in the SQ source code repo, I've found _core.properties_ definition for the web part. And [there is](https://github.com/SonarSource/sonarqube/blob/6.2/sonar-core/src/main/resources/org/sonar/l10n/core.properties) that file. Just for FYI.

**Comment by sergio1990** [comment]
Actually, after the last changes (I mean last 5 commits) the problem with translations on SQ 6.2 has been disappeared 😄

**Comment by shakedlokits** [comment]
Hey Sergey,

It's quite difficult to go through your PR as it is divided into too many commits.
Generally there should be 1 commit <--> 1 Issue. Could you please squash the commits
so we'd have 3 commits s.t:

> - refactor of the part which is responsible for reading and parsing simplecovrcov reports
> - some of the MetricFu rules are marked as BUG
> - a fix (a little bit dirty) of the translations issue, when use this plugin with SonarQube 6.2

As to the dirty fix and your question, it is a standard to create a different branch and release for
different versions. At the moment, the latest LTS version is 5.6.3 and that is why it's supported by the plugin. I will create a 6.2-dev branch so we could start working on the next iteration of the plugin and
we could check how the third patch finds itself in there, maybe we could make it cleaner (:

I've also added Travis CI to the repo and I will configure it on the following days in order to allow integration testing with SonarQube server using the Docker capabilities in Travis in addition to the unit testing.

Thank you,
Shaked

**Review by shakedlokits — CHANGES_REQUESTED** [review]
Please squash into 3 commits respective to your proposed issues and enhancements.

**Comment by sergio1990** [comment]
I've closed this PR in favor to #3 and #4.

**Pull request closed without merging**
